### ISSUE TITLE
Colocar funcionalidades configuráveis

### ISSUE THREAD

**Issue by ipvalverde** [andrerpena/legalone-pacote-melhorias#5]
Deveria haver um popup com as funcionalidades do plugin que permitiria o usuário selecionar somente as funcionalidades que ele deseja.
Dessa forma podemos "desligar" uma funcionalidade.

Sugerido pelo João Bosco.

**Comment by andrerpena** [comment]
Isso é algo que faria sentido se o plugin tivesse um monte de funcionalidades.. o que não acontece agora. Eu considero as 2 funcionalidades que temos agora como "senso comum" então isso ainda não faz sentido, na minha opinião. Eu vou deixar essa issue aberta pra quando fizer sentido.

**Comment by andrerpena** [comment]
Funcionalidades que são injetadas 100% por JavaScript, são facilmente passíveis de serem configuráveis. Porém, funcionalidades que dependem de CSS customizados não. Por mais que seja possível injetar CSS via JavaScript, condicionalmente, às configurações, em alguns casos isso causa flicking.. O menu, por exemplo, que é a funcionalidade mais "controversa", ia dar um flicking enorme se o CSS fosse injetado via JavaScript.

Portanto, por enquanto, infelizmente, as propriedades não vão poder ser configuráveis.
